window.appState = {
  activeView: 'dashboard',
  sidebarOpen: false,
  clientsQuery: '',
  clientsFilter: 'AZ',
  subscriptionsQuery: '',
  clientSummaries: null,
  subscriptionRecords: null,
  accountsCache: null,
  loadError: null,
  suscripcionARenovar: null,
  clienteActualId: null,
  clientesGlobal: [],
  resultContent: null,
  clientesCache: [],
  clienteSeleccionadoId: null,
  suscripcionEditando: null,
  cuentaEditando: null,
  suscripcionABaja: null,
  clienteEditandoId: null,
  estadoFiltroGlobal: 'TODOS',
};
